name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This grants write access to the GITHUB_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version

      # ... your build steps ...

      - name: Deploy to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to gh-pages" || true # `|| true` to avoid failure if no changes
          git push origin HEAD:gh-pages --force